# Generated by Django 3.0.6 on 2020-05-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_duplicates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
